all:
	g++ -Wall -Wextra -Wfatal-errors -pedantic-errors -Iinclude -Iinclude/sdl2 -Iinclude/headers -Iinclude/nlohmann/json/single_include/ -Llib -static-libgcc -static-libstdc++ -ggdb  -o Main src/*.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf

